### PR TITLE
Ja translation

### PR DESCRIPTION
**Pull request by Yosuke-Nozawa**
5 pages are translated in Japanese.

### CODE REVIEW

**Comment by gierschv** [comment]
Thank you! Please don't remove any english files while adding new ones :) .

**Comment by Yosuke-Nozawa** [comment]
> Thank you! Please don't remove any english files while adding new ones :) .
Oops! Sorry. Please let me know Which file I deleted. Thanks!

**Comment by gierschv** [comment]
`docs/en/general/faq-mobile-app.md`, I restored it, you should be able to have it from the last `master` update. Thanks

**Comment by Yosuke-Nozawa** [comment]
> `docs/en/general/faq-mobile-app.md`, I restored it, you should be able to have it from the last `master` update. Thanks

Ok! Thanks.

**Pull request merged**
